// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/timeSeriesService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "edgecom.ai/timeseries/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockTimeSeriesService is a mock of TimeSeriesService interface.
type MockTimeSeriesService struct {
	ctrl     *gomock.Controller
	recorder *MockTimeSeriesServiceMockRecorder
}

// MockTimeSeriesServiceMockRecorder is the mock recorder for MockTimeSeriesService.
type MockTimeSeriesServiceMockRecorder struct {
	mock *MockTimeSeriesService
}

// NewMockTimeSeriesService creates a new mock instance.
func NewMockTimeSeriesService(ctrl *gomock.Controller) *MockTimeSeriesService {
	mock := &MockTimeSeriesService{ctrl: ctrl}
	mock.recorder = &MockTimeSeriesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeSeriesService) EXPECT() *MockTimeSeriesServiceMockRecorder {
	return m.recorder
}

// GetByQuery mocks base method.
func (m *MockTimeSeriesService) GetByQuery(ctx context.Context, q models.TimeSeriesQuery) (models.TimeSeriesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQuery", ctx, q)
	ret0, _ := ret[0].(models.TimeSeriesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByQuery indicates an expected call of GetByQuery.
func (mr *MockTimeSeriesServiceMockRecorder) GetByQuery(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQuery", reflect.TypeOf((*MockTimeSeriesService)(nil).GetByQuery), ctx, q)
}

// GetLatestDataPointTimestamp mocks base method.
func (m *MockTimeSeriesService) GetLatestDataPointTimestamp(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestDataPointTimestamp", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestDataPointTimestamp indicates an expected call of GetLatestDataPointTimestamp.
func (mr *MockTimeSeriesServiceMockRecorder) GetLatestDataPointTimestamp(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestDataPointTimestamp", reflect.TypeOf((*MockTimeSeriesService)(nil).GetLatestDataPointTimestamp), ctx)
}
